### ISSUE TITLE
Userstory 1

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#1]
## Value Proposition

**As a** User 
**I want to** have all my projects at a glance
**so that**  I have a good and quick overview.

## Description

<img width="396" alt="Bildschirmfoto 2023-01-20 um 11 12 56" src="https://user-images.githubusercontent.com/116880659/213670841-56cadf8a-edec-4e22-b9ff-13f68643f923.png">

## Acceptance Criteria

- [ ]  title is positioned fixed on top of the screen
- [ ] a list of all projects is displayed
- [ ] the respective project title is displayed for each list item
- [ ] all project items from static json are displayed as cards

## Tasks

- [ ] create a title component
- [ ] generate a card component for all project items
- [ ] position the title component on top of the landingpage
- [ ] add basic styling 

## Complexity

S

**Comment by kisa5** [comment]
updated my description

**Comment by F-Kirchhoff** [comment]
Hey Anna,
this looks almost perfect, I have only very small change requests:
- instead of each project title is displayed for all list items you want "the respective project title"
- you "position" the title component instead of "fix"
- your last task is an acceptance criteria, so you have to move it in that category
- in the tasks you can add something about generating a card component for all project items

**Comment by kisa5** [comment]
@F-Kirchhoff Alright! I updated your recommended changes. 🙂

**Comment by mbosselmann** [comment]
Hi Anna,
a well defined and small user story! :octocat: 
I only have one note:

You probably don't need an extra title component to get started. You can also just work with an h1 on your homepage and it would work just as well. But if you explicitly want the position fixed, so if you want "Projects" to remain visible as a title even when scrolling down, then this fits. Your wireframe only looks like the user doesn't have to scroll at the beginning.

But this not does not hinder me in approving this user story! 🚀 

Happy hacking! 💪
