### ISSUE TITLE
Userstory 5 

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#10]
## Value Proposition

**As a** User
**I want to** search for my projects
**so that** I don't have to scroll through all of them.

## Description

![Bildschirmfoto 2023-02-01 um 11 52 08](https://user-images.githubusercontent.com/116880659/216024729-f3c67daf-40d5-468b-80c5-4a3607294d29.png)

## Acceptance Criteria

- [ ] directly under the title is a search input
- [ ] in the search input you can type in your project you're looking for 
- [ ] when I type something in the search input, the matching projects get listed for me

## Tasks

- [ ] set State for the search term
- [ ] create a search bar 
- [ ] give the search bar a onChange 
- [ ] create a filter function 
- [ ] combine the filter with the map function 

## Complexity

S

**Comment by niklasrammelkamp** [comment]
Nice one. 🦾
