### ISSUE TITLE
Userstory 6 

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#12]
## Value Proposition

**As a** User
**I want to** be asked again if I really want to delete my project or my task 
**so that** I don't accidentally delete one or change my mind.

## Description

![Bildschirmfoto 2023-02-02 um 10 31 36](https://user-images.githubusercontent.com/116880659/216286234-16672c05-73db-4db9-97de-19ab69ad3cdd.png)

## Acceptance Criteria

- [ ] by clicking on the delete button for the project a window appears asking if I really want to delete the project
- [ ] by clicking on the delete button for the task a window appears asking if I really want to delete the task  
- [ ] you have two options: clicking on the no button and clicking on the yes button 
- [ ] by clicking on the no button the window closes
- [ ] by clicking on the yes button the project or task will be deleted and the window closes

## Tasks

- [ ] build a Modal component
- [ ] build a ModalDelete component
- [ ] set the state for the modal
- [ ] hand over the delete function in the delete modal component 

## Complexity

M

**Comment by JoergWolff** [comment]
LGTM
