### ISSUE TITLE
Userstory 7

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#14]
## Value Proposition

**As a** User
**I want to** check my tasks
**so that** I can get an overview of my completed and uncompleted tasks.

## Description

![Bildschirmfoto 2023-02-02 um 15 28 37](https://user-images.githubusercontent.com/116880659/216351926-55491f4f-3ffd-4eed-b51b-67d8c21726ef.png)

## Acceptance Criteria

- [ ] with every task ist a checkbox listet
- [ ] you can check and un check the checkbox

## Tasks

- [ ] map a checkbox with every task
- [ ] set the local state for it 

## Complexity

s

**Comment by RobinWitt** [comment]
Looks good to me, nice feature.
