### ISSUE TITLE
Userstory 8 

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#17]
## Value Proposition

**As a** User
**I want to** add notes to my project
**so that** I can hold on to my thoughts.

## Description
<img width="430" alt="Bildschirmfoto 2023-02-08 um 14 26 15" src="https://user-images.githubusercontent.com/116880659/217542978-55f99897-c42e-427f-b06b-9ef7a25a8f9d.png">

## Acceptance Criteria

- [ ] on the project page is a text area where you can add your notes
- [ ] next to the text area is a submit button 

## Tasks

- [ ] build a form for the notes section
- [ ] build a handleSubmit function 
- [ ] build a handleNote function for managing the state 

## Complexity

S

**Comment by niklasrammelkamp** [comment]
looks good to me
