### ISSUE TITLE
Userstory 9

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#19]
## Value Proposition

**As a** User
**I want to** have a nice styled app
**so that** it makes more fun to use it.

## Description

![Bildschirmfoto 2023-02-13 um 10 08 40](https://user-images.githubusercontent.com/116880659/218434153-e272ca74-b9a9-4bac-8eee-612fc7530a59.png)

## Acceptance Criteria

- [ ] main three colours are blue grey and white
- [ ] the name of the app is fixed on top 
- [ ] background is in a light color
- [ ] the project and task cards have the same color 
- [ ] the delete button has a trash can icon
- [ ] every input has a blue border

## Tasks

- [ ] work with styled components
- [ ] set global font to helvetica 
- [ ] set the app name on top of the screen
- [ ] import trash icon
- [ ] style the components in the colors blue and grey 

## Complexity

L
