### ISSUE TITLE
Userstory 2

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#2]
## Value Proposition

**As a** User
**I want to** add a new project 
**so that** I can start planning it.

## Description

<img width="713" alt="Bildschirmfoto 2023-01-20 um 11 30 31" src="https://user-images.githubusercontent.com/116880659/213674917-90581048-3460-4ff9-bdb1-05034e09b88a.png">

## Acceptance Criteria

- [ ] input field where you can add your new project
- [ ] add button to add your project to the other ones
- [ ] by submitting the button your new project appears 

## Tasks

- [ ] add a form for your project 
- [ ] add a submit button 

## Complexity

S
