### ISSUE TITLE
Userstory 3

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#5]
## Value Proposition

**As a** User 
**I want to** add a project and tasks
**so that** I don't lose my ideas

## Description

![Bildschirmfoto 2023-01-24 um 11 09 53](https://user-images.githubusercontent.com/116880659/214264864-8ed5a45a-d96e-48eb-8d20-6ce49d9f3c08.png)

## Acceptance Criteria

landing page:
- [ ] input field to type in your new project title
- [ ] next to input field: submit button for adding your new project

project page:
- [ ] input field to type in your task title
- [ ] next to input field: submit button for adding your new task

## Tasks

landing page:
- [ ] create a form with an text input for the project title
- [ ] create a button with a submit function for adding the project 

project page:
- [ ] create a form with an text input for the task 
- [ ] create a button with a submit function for adding the task

## Complexity

M

**Comment by RobinWitt** [comment]
The only thing I would change is the Value Proposition. Suggestion: "As a User
I want to add new projects and tasks...
...so I don't lose my ideas"
or
...so I can keep track of them"

Apart from that, it is a very good user story, descriptive, clear, and has good complexity! Nice!
