### ISSUE TITLE
Userstory 4

### ISSUE THREAD

**Issue by kisa5** [kisa5/capstone-project#7]
## Value Proposition

**As a** User
**I want to** delete my projects and tasks
**so that** I get rid of them.

## Description

![Bildschirmfoto 2023-01-26 um 11 33 54](https://user-images.githubusercontent.com/116880659/214815195-116d8d01-296e-497c-95ab-0baa4b84c938.png)

## Acceptance Criteria

- [ ] there is a delete button on every project
- [ ] there is a delete button on every task

## Tasks

- [ ]  create a button with a handle a onClick function for the delete 
- [ ] set the delete button on the projects
- [ ] set the delete button on the tasks

## Complexity

S
